//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace alljoyn { namespace example { namespace Sonar {

public interface class ISonarService
{
public:
    // Implement this function to handle calls to the Stop method.
    Windows::Foundation::IAsyncOperation<SonarStopResult^>^ StopAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the Start method.
    Windows::Foundation::IAsyncOperation<SonarStartResult^>^ StartAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the Speech method.
    Windows::Foundation::IAsyncOperation<SonarSpeechResult^>^ SpeechAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

};

} } } } 
