
//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

#include <windows.h>
#include <ppltasks.h>
#include <concrt.h>
#include <collection.h>
#include <windows.devices.alljoyn.interop.h>
#include <map>

#include <alljoyn_c/busattachment.h>
#include <alljoyn_c/dbusstddefines.h>
#include <alljoyn_c/AboutData.h>
#include <alljoyn_c/AboutObj.h>
#include <alljoyn_c/AboutObjectDescription.h>

#include "AllJoynHelpers.h"
#include "AllJoynBusObjectManager.h"

#define PROJECT_NAMESPACE org::alljoyn::example::Sonar

#include "SonarStructures.h"
#include "TypeConversionHelpers.h"
#include "SonarMethodResults.h"
#include "SonarEventArgs.h"
#include "ISonarService.h"
#include "SonarSignals.h"
#include "SonarProducer.h"
#include "SonarWatcher.h"
#include "SonarConsumer.h"
#include "SonarServiceEventArgs.h"
#include "SonarServiceEventAdapter.h"