//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

using namespace concurrency;

namespace org { namespace alljoyn { namespace example { namespace Sonar {

ref class SonarConsumer;

public ref class SonarStopResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static SonarStopResult^ CreateSuccessResult()
    {
        auto result = ref new SonarStopResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }
    
    static SonarStopResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new SonarStopResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

public ref class SonarStartResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static SonarStartResult^ CreateSuccessResult()
    {
        auto result = ref new SonarStartResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }
    
    static SonarStartResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new SonarStartResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

public ref class SonarSpeechResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static SonarSpeechResult^ CreateSuccessResult()
    {
        auto result = ref new SonarSpeechResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }
    
    static SonarSpeechResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new SonarSpeechResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

public ref class SonarJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property SonarConsumer^ Consumer
    {
        SonarConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ SonarConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    SonarConsumer^ m_consumer;
};

} } } } 
